### ISSUE TITLE
iPhone 5,2 9.3.1 offsets? cant seem to find only those here...

### ISSUE THREAD

**Issue by mark8598** [benjamin-42/Trident#103]
Is it even possible to jailbreak iPhone 5,2 on 9.3.1 so it isnt included anywhere or?

**Comment by P0SlX** [comment]
Soon I will create a PR for all iPhone5,2 offsets, with trident, you can only have root access but with Home depot you can jb

**Comment by P0SlX** [comment]
Hey, try this offsets on jk9357's jb IPA:

0x31EF50
0x321810
0x1EE6C
0xDEA48
0x40B428
0xCB7DC
0xDEA4A
0xCB508
0x45D978
0x3FE454
0xCB560
0x45F2C8
0xA4

Comment if it works please :)

**Comment by aleondopeso** [comment]
Those offsets works on iOS 9.3.1 iPhone 5,2

**Comment by mark8598** [comment]
Ty so much! It works, some tweaks arent supported but oh well there are always replacements :))

**Comment by P0SlX** [comment]
Glad that helped you :)
