### ISSUE TITLE
can you add support to iphone 5,4 9.3.1

### ISSUE THREAD

**Issue by shawnchenx6** [benjamin-42/Trident#105]

**Comment by Dixyder** [comment]
You can found offsets of it on this: https://www.reddit.com/r/jailbreak/comments/5vpuyf/discussion_list_of_all_iphone_all_ipad_will_be/?st=1Z141Z3&sh=66a774de
Use Home Depot and enter you offsets for you device and version

**Comment by P0SlX** [comment]
You can find your offsets on this link https://www.reddit.com/r/jailbreak/comments/5vpuyf/discussion_list_of_all_iphone_all_ipad_will_be/?st=1Z141Z3&sh=66a774de
Just search for your device and your version tell me if it works

**Comment by benjamin-42** [comment]
Will close for now, note that there is no specific plan on this, but @Dixyder is pushing it :)
