### ISSUE TITLE
Offset Help

### ISSUE THREAD

**Issue by OothecaPickle** [benjamin-42/Trident#106]
How do I find these:
find_setreuid_cred_update()
find_pid_check()
find_posix_check()
find_mac_proc_check()

**Comment by benjamin-42** [comment]
For the first one, first find setreuid syscall (with joker tool for example), at the beginning of the function there are some checks, the idea is to jump after those checks.
The last 3 are related to task_for_pid, I'd recommend to look at its source code, you will find a way to find it in iOS firmware (it checks for pid == 0 and call proc_find at the beginning of the function).
Also take a look at the guide by @angelXwind in the README file
