### ISSUE TITLE
App Message: Offsets not found for iPhone 5,1 - iOS 9.3.3

### ISSUE THREAD

**Issue by xbliss** [benjamin-42/Trident#111]
I just got a message today from the App: Offsets not found for iPhone 5,1 - iOS 9.3.3
Anyone / any thoughts? 

How can I go about finding the offsets - Karen's How To is not clear enough. 

I've done programming/ development in my younger life and used HexTools in college so I am wondering how to proceed?

**Comment by benjamin-42** [comment]
It seems that you don't have the latest version of the project, I can see iPhone51_iOS933 in offsetfinder. Anyway, offsets are referencing some code, function or data structure, for some of them you can find information. For others you can still compare with offsets of a known firmware to help you.

**Comment by xbliss** [comment]
I got the offset but I am facing a new issue now. 

I am unable to re-enable the Jailbreak after the installation of iCleaner Pro.  Also, unable to start the phone in Safe/ Substrate mode where the JB phone starts without other "daemons" in/ installed via Cydia.
