### ISSUE TITLE
 iPad3,4 (iPad 4 Wifi) 9.3.1 - Jailbreak lost after every reboot

### ISSUE THREAD

**Issue by Experte** [benjamin-42/Trident#114]
I ve jailbroken an iPad3,4 (iPad 4 Wifi) 9.3.1 using "Home depot" with custom offsets. every thing went well. but after every reboot the jailbreak is lost and have to rejailbreak everytime.

**Comment by kevyboy201222** [comment]
its semi tethered no untethered

On 2017-03-25, at 6:13 AM, "Experte" <notifications@github.com<mailto:notifications@github.com>> wrote:


I ve jailbroken an iPad3,4 (iPad 4 Wifi) 9.3.1 using "Home depot" with custom offsets. every thing went well. but after every reboot the jailbreak is lost and have to rejailbreak everytime.
