### ISSUE TITLE
I need offsets for iPhone 4,1 iOS 9.3.4

### ISSUE THREAD

**Issue by ghost** [benjamin-42/Trident#115]
Hello I need the offsets for iPhone 4,1 iOS 9.3.4 I changed my system version while jailbroken and now I can't re-enable my jailbreak so I need custom offsets so please post the offsets. I don't have the skill to find them myself so please post them someone. (iPhone 4S iOS 9.3.4 Trident Offsets)

**Comment by P0SlX** [comment]
I've created a month ago a thread on reddit for custom offsets use in Home Depot and all devices in all iOS version is listed bellow: https://redd.it/5vpuyf if you want to check this out
