### ISSUE TITLE
about how to install openssh after run this app

### ISSUE THREAD

**Issue by dawnworld** [benjamin-42/Trident#12]
I compiled and run it in my iphone4s (ios 9.3.2), it displayed that "w00t root". now I want to install `openssh` or `cydia`, who can help me?

**Comment by EGYbkgo9449** [comment]
that's what I'm going to work on after the JB succeed for my iPhone

DM (or Tweet me if u can't) me on Twitter "Twitter.com/SpRay_BestTube" if u want to help ;)

**Comment by benjamin-42** [comment]
@dawnworld If you want to run those binaries you need to patch more kernel code, for sandbox and code signing enforcement. This is not included in the project for now, please look at README file.
