### ISSUE TITLE
The project is not working in Xcode 7

### ISSUE THREAD

**Issue by paul2048** [benjamin-42/Trident#13]
I tried like 3 days in a row to set-up a VM on Mac OS X Yosemite but the latest version of Xcode is not supported.
A iPA file would be awesome so I could use it with Cydia Impactor.

**Comment by EGYbkgo9449** [comment]
It doesn't work with the iPhone 5,2 & 5,3 yet 😔

**Comment by benjamin-42** [comment]
@VeryKnave Install El Capitan/Sierra to use the latest version of Xcode - I won't distribute an IPA with current project state.
