### ISSUE TITLE
iphone 5 .4 need your help

### ISSUE THREAD

**Issue by bugleigt** [benjamin-42/Trident#20]
![192392914548155569](https://cloud.githubusercontent.com/assets/24838810/21561645/4d1d3ce8-ceaa-11e6-8b30-b58cdc2b0eeb.jpg)
this is a Sad story 
I'd like to test out for you.
   please

**Comment by EGYbkgo9449** [comment]
Tweet me on Twitter.com/SpRay_BestTube and I'll DM u to add the device, don't worry it's very easy :)

Once it works I'll push the updated files here ;)

**Comment by benjamin-42** [comment]
No specific date/plan for other devices support, might be supported in the future but I can't guarantee
