### ISSUE TITLE
Support for IPhone 4s IOS 9.2.1 

### ISSUE THREAD

**Issue by singhstar123** [benjamin-42/Trident#23]
So I installed Trident on my device it says that it is not supported. I have a iphone 4s 9.2.1 (13D15), Is there any way to allow it to be supported on my device? Thank you, I am not much experienced within this field but do have enough knowledge to get the job done.

**Comment by benjamin-42** [comment]
No specific date/plan for this, maybe someone will add support for it by patching offsets. There is a guide written by @angelXwind, look at README file.
