### ISSUE TITLE
iPad3,1 iOS 9.3.3 Support

### ISSUE THREAD

**Issue by joshuawins99** [benjamin-42/Trident#25]
Can you add support for the Wifi only iPad 3rd Gen on iOS 9.3.3.

**Comment by pozzdonnz79** [comment]
Noooo that not fair bro it should release all version support together no matter what happen let it happen I can wait just make the best why ask just release WiFi ?,what about CDMA and Gsm ?,no no that not nice if it fuckup we fucked together

**Comment by pozzdonnz79** [comment]
Did you see list they has release for ipad3 WiFi only not support Gsm CDMA you can root then install open ssh for downgrade or install cydia and install dual boot for switch 8.x-9.x

**Comment by benjamin-42** [comment]
No specific date/plan for this, maybe someone will add support later

**Comment by pozzdonnz79** [comment]
Thanks ben
