### ISSUE TITLE
Offsets iPad 3,3 iOS 9.3.2

### ISSUE THREAD

**Issue by f0xyru** [benjamin-42/Trident#33]
Please, test it. On my iPad 3.3 with 9.3.2 - it's work fine.

<img src="http://f0xy.ru/IMG_0695.JPG" style="max-width:30%;">

find_OSSSerializer_serialize(): 0x318264
find_OSSymbol_getMetaClass(): 0x31aa6c
find_calend_gettime(): 0x1e170
find_bufattr_cpx(): 0xd9848
find_clock_ops(): 0x403428
find_copyin(): 0xc76b4
find_bx_lr(): 0xd984a
find_write_gadget(): 0xc73e8
find_vm_kernel_addrperm(): 0x455844
find_kernel_pmap(): 0x3f6454
find_flush_dcache(): 0xbc260
find_invalidate_tlb(): 0xc7440
find_task_for_pid(): 0x2fcd80
find_setreuid(): 0x2a985c
find_pid_check(): 0x14
find_posix_check(): 0x3e
find_mac_proc_check(): 0x1e6

**Comment by ganoninc** [comment]
Good work.

**Comment by benjamin-42** [comment]
@f0xyru good job, can you please open a PR with your offsets? :)

**Comment by MuMuTian** [comment]
为什么，我一点YOLO就黑屏重启，我是5c的手机？？？？？

**Comment by f0xyru** [comment]
@benjamin-42 okay, later :)
