### ISSUE TITLE
How to find offsets?

### ISSUE THREAD

**Issue by ghost** [benjamin-42/Trident#39]
Not all that sure how to find the device offsets, anyone know?

**Comment by ghost** [comment]
Never mind I got it.

**Comment by ghost** [comment]
Nevermind again I don't got it... :P

**Comment by SecurePanda** [comment]
Could you be a bit more specific? There's a pretty good write-up on how to find the offsets, and it provides a helpful link to the kcache tool (whose readme provides an example of how to use it.)

**Comment by ghost** [comment]
So, I'm trying to find the offsets for a few devices that currently aren't supported in the Trident jailbreak. I have looked at AngelXwind's tutorial, though it was not very clear to me. Is the _write-up_ you're talking about different from the one on AngelXwind's website?

**Comment by SecurePanda** [comment]
It's the same. Are you using IDA, Hopper, or something else to search the decrypted kernelcache?

**Comment by benjamin-42** [comment]
You can compare offsets from supported firmware to help you, you have to find equivalent code/data. There are enough resources available, will close this issue.
