### ISSUE TITLE
A6 devices issues

### ISSUE THREAD

**Issue by KpwnZ** [benjamin-42/Trident#44]
Tested on iPhone 5,2. iOS 9.3.X failed, but iOS 9.2.X works well.

**Comment by testsuen** [comment]
Can you compile IPA?

**Comment by benjamin-42** [comment]
@010X would be great if you could debug and find more information, will close for now as it requires more info

@testsuen no specific plan/date for a compiled IPA, you can install macOS (in a virtual machine if needed) and compile an IPA with Xcode
