### ISSUE TITLE
HALP! iOS 9.3.1 iPod 5,1

### ISSUE THREAD

**Issue by D3C0D3R5** [benjamin-42/Trident#45]
Yo, can anyone confirm that this will soon be out? And in .ipa form? Because i dont have a mac and i cant use xcode to install it. My device is a iPod 5,1 (5th genegration) and i am running iOS 9.3.1 btw pls and thx! :)

**Comment by P0SlX** [comment]
I've an iPod Touch 5 too but on 9.3.3 and no update since 9.3.2. Is it possible to compile it in .ipa file for Windows user ? Because I don't have a Mac

**Comment by D3C0D3R5** [comment]
My question as well, i dont have a mac and so i need it in ipa form aswell, except my ipod 5 is on ios 9.3.1

**Comment by benjamin-42** [comment]
No specific date/plan for this, you can still install a virtual machine with macOS
