### ISSUE TITLE
iPad 3,3 9.3.2??

### ISSUE THREAD

**Issue by TheMorc** [benjamin-42/Trident#46]
i want to include 9.3.2 for iPad 3,3 in Xcode to trident that was in closed issues but i don't know how to add it.

**Comment by TheMorc** [comment]
or, i added it somehow it did show YOLO  and iPad3,3 - iOS 9.3.2 but it should restart after? because it restarted and booted back but again YOLO and iPad not w00t root like on picture.

**Comment by paul2048** [comment]
It should display 'w00t root', so it didn't worked

**Comment by TheMorc** [comment]
update: so i checked code and i found that i forgot to change MetaClass, after compiling and installing to iPad by clicking YOLO it showed w00t root.
