### ISSUE TITLE
Need tester for iPhone41_IOS920 

### ISSUE THREAD

**Issue by ganoninc** [benjamin-42/Trident#58]
Hello,

Is there someone with an iPhone 4S on iOS 9.2 who could check if my offsets are right? 

https://github.com/ganoninc/Trident/tree/ganoninc-iPhone41_IOS920

Thanks

**Comment by benjamin-42** [comment]
@ganoninc will close the issue for now, if someone reports issue for this I will notify you

**Comment by ganoninc** [comment]
So I should open a pull request with my offsets?

**Comment by benjamin-42** [comment]
Yes sure, you found offsets for other devices that are correct so go ahead :)

**Comment by ganoninc** [comment]
Yes but I couldn't find "find_setreuid" so I observed that between iPhone52_iOS920 and iPhone52_iOS921 there is a difference of 0x110

case iPhone52_iOS920: return 0x2a9e24;
case iPhone52_iOS921: return 0x2a9f34;

So based on "case iPhone41_iOS921: return 0x2a3bc4;" I computed that iPhone41_iOS920 should have 0x2a3ab4.

That's why here: https://github.com/ganoninc/Trident/blob/ganoninc-iPhone41_IOS920/Trident/offsetfinder.c (line 805) I wrote "// ? to be verified"


By the way, the difference is the same for iPad22_iOS920 and iPad22_iOS921, iPad22_iOS920 and iPad22_iOS921, iPad23_iOS920 and iPad23_iOS921 and iPad24_iOS920 and iPad24_iOS921
