### ISSUE TITLE
Add Support for iPhone5,1 (N42AP), iOS 9.2.1 (Dillon 13D15)

### ISSUE THREAD

**Issue by K0smas** [benjamin-42/Trident#60]
Is there any difference between iPhone5,1(GSM) and iPhone 5,2(GLOBAL) with respect to finding the correct offsets? or is it a easier fix, possibly just editing the project source to add the 5,1 identifier so the app will pick it up and execute?

**Comment by benjamin-42** [comment]
No idea, download both firmwares and try to see if there is any differences — yes you can try to edit the project to add iPhone5,1 and see if it works
