### ISSUE TITLE
8.4.1 support

### ISSUE THREAD

**Issue by pwn841** [benjamin-42/Trident#61]
I can see that support for downgrading iOS 9.1-9.3.4 is becoming available to an increasing number of devices, which is great for 32 bit users.
Being on 9.2.1 on my 4S, I would downgrade to 8.4.1 because iOS 9 is just slow on the 4S without bringing much, I've been sorry for a year to have upgraded. But for starters I wouldn't want to be stuck on 8.4.1 and only be able to upgrade to the unjailbroken 9.3.5 when iOS 8 would truly be obsolete or when an iOS 9.1-9.3.4 32 bit jailbreak would appear, particularly as I have iOS 9.2.1-9.3.4 SHSH blobs.
I appreciate the work put in so far for jailbreaking iOS 9.1 - 9.3.4 on 32 bit but as it appears that Trident has been used since iOS 7 could you also make it work on the yet-to-be-jailbroken 8.4.1?
Thank you all for your great work!

**Comment by benjamin-42** [comment]
I'm not sure Trident will work on iOS 7, it will require to look for the vulnerabilities inside an iOS 7 firmware. Anyway there is no specific plan for this.
