### ISSUE TITLE
Working Offsets for iPod 5,1 at iOS 9.1

### ISSUE THREAD

**Issue by hexcelsior** [benjamin-42/Trident#63]
Hi Benjamin,

Great work on the Trident implementation 👍 

I'd though I'd post these here instead of a pull request, as adding them to offsetfinder.c doesn't work OTB.

find_OSSerializer_serialize: 0x319450
find_OSSymbol_getMetaClass: 0x31bc3c
find_calend_gettime: 0x1db34
find_bufattr_cpx: 0xd97d0
find_clock_ops: 0x4053cc
find_copyin: 0xc7754
find_bx_lr: 0xd97d2
find_write_gadget: 0xc7488
find_vm_kernel_addrperm: 0x457030
find_kernel_pmap: 0x3f8444
find_flush_dcache: 0xbcb7c
find_invalidate_tlb: 0xc74e0
find_task_for_pid: 0x2fe034
find_setreuid: 0x2aa31c
find_pid_check: 0x16
find_posix_check: 0x40
find_mac_proc_check: 0x224

However, these values won't work without another modification! The new_branch value in patch_setreuid presumes that the branch exists at offset 0xe031 - in this particular kernel, it actually is present at 0xe03e. 

You wouldn't believe what I have had to wade through to get a semi-working kernel dump! I had to take lots of seperate chunks of 0x18000 bytes in size (with Siguza's implementation) and stitch them together as the kernel seems very sensitive to using a read primative! However, with your task_for_pid patch, this issue goes away, and a proper kernel dump can be made with ios-kern-utils!! Thanks so much!

**Comment by NoelTautges** [comment]
Correct me if I'm wrong, but I think 0xe031 is the patched set of instructions, not the offset from setreuid.

Nice work on dumping the kernel, though!

**Comment by hexcelsior** [comment]
Ooops! Totally Right! 
Anyway, it's as simple as changing new_branch to 0xe03e!

(I've been thinking too much about offsets lately, I've had to do lots of calculations!)

**Comment by benjamin-42** [comment]
@hexcelsior you can create a new function in offsetfinder to take this into account, please feel free to open a PR, especially if you managed to get it working :)

**Comment by ganoninc** [comment]
I've sent a pull request with the requested changes :)

https://github.com/benjamin-42/Trident/pull/66
