### ISSUE TITLE
iPod 5,1 9.3.1 Implementation?

### ISSUE THREAD

**Issue by D3C0D3R5** [benjamin-42/Trident#64]
Any release dates for iPod 5,1 on iOS 9.3.1? I really need jailbreak because my phone is running very slow, and its boring because i dont apps like "Barrel" and "iFile" and i wanna install jailbreak apps :( , i mainly got the iPod because i thought jailbreak was already released for it... then i found out that jailbreak was only available for 64bit iOS devices :'(

**Comment by benjamin-42** [comment]
No specific plan/release date for this — moreover this isn't a jailbreak in its current state, please take a look at README file
