### ISSUE TITLE
iPad 2 9.1 

### ISSUE THREAD

**Issue by buyinginquiries** [benjamin-42/Trident#75]
Hi, I tried the new offsets with Trident for my iPad 2,1 9.1, and the application just reboots my iPad. I think there might be something wrong with the offsets. Thanks!

**Comment by benjamin-42** [comment]
@buyinginquiries can you please try again with latest changes?

**Comment by benjamin-42** [comment]
Closing this one, if you still experience crashes please open a new issue with more information
