### ISSUE TITLE
Application restart on iPhone 5,2

### ISSUE THREAD

**Issue by brazier19971** [benjamin-42/Trident#78]
Trident app seems to crash to home screen on iPhone 5,2 on iOS 9.2. Some kernel panics too. Error log: pastebin.com/DQWVuKR9

**Comment by 1Conan** [comment]
Home Depot != Trident

On the side note, I have posted the correct offsets for homedepot on reddit. Use that. (I have the same iPhone and iOS version and I'm currently enjoying my Jb)

**Comment by brazier19971** [comment]
Yeah, tried that and working very well now!

**Comment by benjamin-42** [comment]
@1Conan so is there an issue with the one in this repository? if yes can you please open a PR for those ones too? Thank you very much

**Comment by 1Conan** [comment]
@benjamin-42
The Home Depot app doesn't have the two last offsets that it requires for 9.2.x

This is the reason for the crashes. Offsets I posted for Home depot contains the offsets I submitted here and the two pffsets for 9.2 that Home Depot requires
