### ISSUE TITLE
patch_task_for_pid instruction patch offset issue

### ISSUE THREAD

**Issue by nanidayo** [benjamin-42/Trident#8]
The offsets for the instructions that need to be patched should also be abstracted. For example; the iPhone 5,2 9.3.1 is at an offset of 0x16, whereas the iPad 3,1 9.3.4 is at 0x14. This may also be present in other devices / firmware.

![](http://puu.sh/sRojN/7d070dab03.png)

Perhaps implement a find_patch_task_for_pid_offsets(unsigned patch_number); function?

Example:
```
u_int32_t find_task_for_pid_patch_offsets(unsigned patch_number) {
    switch (patch_number) {
        case 1:
            switch (target_environment) {
                case iPhone52_iOS931: return 0x16;
                default: return 0x14;
            }
        case 2:
            switch (target_environment) {
                default: return 0x3e;
            }
        case 3:
            switch (target_environment) {
                default: return 0x1e6;
            }
        default: abort();
    }

}
```

Also, the only reason I have the case 2 and case 3 is incase there's any difference for those instructions too. The first instruction might be the only one. If so you can leave those out and just return 0x3e and 0x1e6 respectively.

Update: This is also the same with patch_setruid(). The offsets are different. 
Update update: There also seems to be some issues with the pmap patch? Is the pmap patch dependent on any offsets other than the kernel_pmap base itself?

**Comment by akemin-dayo** [comment]
This feature already exists: https://github.com/benjamin-42/Trident/blob/master/Trident/offsetfinder.c#L305

See `uint32_t find_pid_check(void)` `uint32_t find_posix_check(void)` and `uint32_t find_mac_proc_check(void)`.

**Comment by nanidayo** [comment]
@angelXwind That wasn't committed when I posted this :s
