### ISSUE TITLE
iphone4,1 ios9.3beta offsets？

### ISSUE THREAD

**Issue by mohexyl** [benjamin-42/Trident#82]
ios9.3beta

**Comment by ganoninc** [comment]
I have offsets for the BETA 2 here: https://github.com/ganoninc/trident-kloader-updated/blob/iPhone4S-on-iOS-9.3.3-Beta-2/Trident/offsetfinder.c

**Comment by mohexyl** [comment]
i need 9.3.0beta

**Comment by mohexyl** [comment]
or how to find offsets！

**Comment by mohexyl** [comment]
please i need offsets to jailbreak

**Comment by benjamin-42** [comment]
No specific plan/date for this, someone may add those offsets in the future
