### ISSUE TITLE
Can you add support for ipad 2,5 ios 9.3.4.

### ISSUE THREAD

**Issue by teblok** [benjamin-42/Trident#87]
i've had a look around and seen the amount of versions you have for ipad, but no support for mini 1.
ive seen tutorials on youtube on how to add support, but im on a windows machine and cant do that (i dont want do go through the hassle of virtual machines). anyway if you can make this happen, great, but in the meen time im just going to wait.

**Comment by benjamin-42** [comment]
No specific plan/date for this, maybe someone will add those offsets in the future
