### ISSUE TITLE
iPad3.1 iOS 9.3.3

### ISSUE THREAD

**Issue by azimys544** [benjamin-42/Trident#91]
I read another closed issue,but...any hope for that one?It's so strange that higher version (9.3.4) supported and lower one not :(
Anyway, best regards and good luck with the project!

**Comment by benjamin-42** [comment]
It isn't strange, the thing is that originally this code was only targeting iOS 9.3.4 for iPad3,1 so there are a lot of hardcoded offsets. There could be less offsets by dumping kernel memory as early as possible and deduce offsets from this dump — I don't think I'll invest time on this.
