### ISSUE TITLE
What would have to been changed in this project to add support for iOS 8.4.1?

### ISSUE THREAD

**Issue by OothecaPickle** [benjamin-42/Trident#96]
I will comply if told to close this issue, but I'm just wondering if it's possible. Thanks in advance, Zach.

**Comment by benjamin-42** [comment]
I don't know to be honest and I won't check, but what you can do is looking for those vulnerabilities in XNU source code, a version close to what was shipped with iOS 8.4.1 (XNU 2784.40.6~18 apparently) and look at Lookout paper (link in README file)
