### ISSUE TITLE
Offsets for iPhone5,1 9.1 expect setreuid

### ISSUE THREAD

**Issue by P0SlX** [benjamin-42/Trident#99]
I've found offsets for iPhone5,1 on 9.1 expect streuid, I can't find it so if anyone can find it please comment below I will create a PR.
find_OSSerializer_serialize()	        
0x31fd1c

find_OSSymbol_getMetaClass()	
0x322460

find_calend_gettime()			
0x1e76c

find_bufattr_cpx()				
0xde9fc

find_clock_ops()				
0x40c5a0

find_copyin()					
0xcb87c

find_bx_lr()					
0xde9fe

find_write_gadget()				
0xcb5a8

find_vm_kernel_addrperm()		
0x45e0fc

find_kernel_pmap()				
0x3ff444

find_flush_dcache()				
0xbf770

find_invalidate_tlb()			        
0xcb600

find_task_for_pid()				
0x3040a4

find_setreuid()	
				
find_setreuid_cred_update()		
0xe031

find_pid_check()				
0x16

find_posix_check()			
0x3e

**Comment by benjamin-42** [comment]
@Dixyder use "joker -s" to find setreuid http://newosxbook.com/tools/joker.html

**Comment by P0SlX** [comment]
But I don't have a Mac, can I run this on Linux ?

**Comment by benjamin-42** [comment]
There is a 64-bit version for Linux, please look at the link
